name: Build AIO-switch-updater

on: [push]
jobs:
  AIO-switch-updater:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        git submodule update --init --recursive

    - name: Update libnx to 4.0.
      run: |
        pacman -S libnx>=4.0
        
    - name: Building aio-switch-updater
      run: |
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: aio-switch-updater
        path: aio-switch-updater*.nro
